- hosts: cluster 
  become: yes
  gather_facts: yes

  vars_files:
    - dep7server_vault.yml 
  
  pre_tasks:
    - name: Add a line to a file if the file does not exist, without passing regexp
      lineinfile:
        path: /etc/cloud/cloud-init.disabled
        line: cloud-init=disabled
        create: yes
        state: present
  
    - name: Run the equivalent of "apt-get update" as a separate step
      apt:
        update_cache: yes

    - name: Find timezone
      command: timedatectl 
      register: timedate_output
      changed_when: false

    - name: Set time zone
      command: timedatectl set-timezone Europe/Moscow
      when: '"Moscow" not in timedate_output.stdout'

  roles:
    - ansible-ntp-master
    - geerlingguy.docker